---
language: java
sudo: false
env:
  global:
  - LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/travis/lib/ubuntu-12.04.5-amd64
  - BUILD_IDV=false
matrix:
  include:
  - jdk: oraclejdk7
  - jdk: oraclejdk8
  - jdk: openjdk7
script:
- if [[ $BUILD_IDV == true ]]; then travis/build_idv.sh; fi
- if [[ $BUILD_IDV == false ]]; then ./gradlew --info testAll; fi
cache:
  directories:
  - "$HOME/.gradle"
