---
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
env:
  global:
  - MAVEN_OPTS="-Djna.library.path=/usr/local/lib -DskipTests=false -DfailIfNoTests=false"
  - NCVERSION=4.3.2
before_install:
- sudo apt-get install libhdf5-serial-dev
- wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-${NCVERSION}.tar.gz
- tar xf netcdf-${NCVERSION}.tar.gz
- cd netcdf-${NCVERSION}
- "./configure --prefix=/usr/local"
- make
- make check || true
- sudo make install
- cd ..
install:
- mvn install -DskipTests=true
script:
- cd cdm && mvn test ${MAVEN_OPTS}
- cd ../udunits && mvn test ${MAVEN_OPTS}
- cd ../ui && mvn test ${MAVEN_OPTS}
- cd ../waterml && mvn test ${MAVEN_OPTS}
- cd ../dap4/d4tests && mvn test ${MAVEN_OPTS}
cache:
  directories:
  - "$HOME/.m2"
