---
language: java
sudo: false
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
script:
- "./gradlew --info :cdm:test :grib:test :udunits:test :ui:test :waterml:test"
cache:
  directories:
  - "$HOME/.gradle"
